version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - target=dev
    environment:
      PORT: 8080
      DB_NAME: bstodo
      DB_PASS: password
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bstodo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  db_data:
