// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Priority struct {
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Name            string
	InvitationToken string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ProjectUser struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Role struct {
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Done        bool
	Priority    string
	DueDate     sql.NullTime
	ProjectID   uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Auth0ID   string
	Name      string
	Email     string
	Picture   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
