// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Priority struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Todo struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Done        bool       `json:"done"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"due_date"`
	Auth0ID     string     `json:"auth0_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}
